### ISSUE TITLE
How might this work with UIApplicationDelegate?

### ISSUE THREAD

**Issue by hokster7** [foursquare/FSQMessageForwarder#1]

**Comment by bdorfman** [comment]
Well first of all, I don't really recommend doing this. But if you really want to...

The app delegate is instantiated for you so you can't just pass in a bare FSQMessageForwarder. I would create a custom subclass of the forwarder that sets up its own children in its init method and then pass that subclass in as the delegate class in your main.m file. That should probably work ok.

Again, probably not a good idea, and proceed at your own risk. Hope that helps!

**Comment by hokster7** [comment]
@bdorfman Good to know, thanks!
